[package]
name = "mullvad-cli"
version = "2018.3.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Manage the Mullvad VPN daemon via a convenient CLI"
license = "GPL-3.0"

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
clap = "2.20"
error-chain = "0.12"
env_logger = "0.5"
serde = "1.0"
futures = "0.1"

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }
talpid-ipc = { path = "../talpid-ipc" }

[target.'cfg(windows)'.build-dependencies]
windres = "0.2"
